spring:
  application:
    name: SpringBoot-MongoDB

  data:
    mongodb:
      host: localhost
      port: 27017
      database: mongodb9Jun24
      username: root
      password: root
server.port: 8080
# Increase async request timeout (in milliseconds)
spring.mvc.async.request.timeout: 60000